[pytest]
markers =
    smoke: smoke test
    sanity: sanity test
    str: string test
    strtest

# Add the specified OPTS to the set of command line arguments as if they had been specified by the user.
addopts = --maxfail=4

# collect tests from classes that end in Suite:
python_classes = *Suite

# By default, files matching test_*.py and *_test.py will be considered test modules.
python_files = test_*.py *_test.py check_*.py

# By default, pytest will consider any function prefixed with test as a test.
# Example of how to collect test functions and methods that end in _test:
python_functions = *_test test*

# list of directories that should be searched for test, when no specific directories, files or test ids are given in the command
# by default all subfolders are searched
# testpaths = Pytest_topics\\py_fixtures

# List of fixtures that will be applied to all test functions;
# this is semantically the same to apply the @pytest.mark.usefixtures marker to all test functions.
;usefixtures =
;    setup_list